services:
    db:
      container_name: sdi_db
      image: postgres:alpine
      env_file:
        - env
      ports:
        - "54332:5432"
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 5
      networks:
        - sdi
    dev:
        container_name: sdi-dev
        tty: true
        build:
            context: .
            dockerfile: Dockerfile
            target: build
        env_file:
          - env
        ports:
            - "8999:8080"
            - "8998:4000"
        networks:
          - sdi
        volumes:
          - ./:/go/src/app/
    sdi:
      container_name: sdi
      tty: true
      build:
          context: .
          dockerfile: Dockerfile
      env_file:
        - env
      ports:
          - "8997:8080"
      networks:
        - sdi
      volumes:
          - prod-data:/opt/sportix/pb_data/
      restart: always
    

networks:
  sdi:
    driver: bridge
  
volumes:
  prod-data:
