version: '3'

services:
    db:
      container_name: sdi_db
      image: postgres:alpine
      env_file:
        - env
      ports:
        - "5433:5432"
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 5
      networks:
        - sdi
    dev:
        container_name: sdi-dev
        tty: true
        build:
            context: .
            dockerfile: Dockerfile
            target: build
        env_file:
          - env
        ports:
            - "8999:8080"
        depends_on:
          db:
            condition: service_healthy
        networks:
          - sdi
        volumes:
          - ./:/go/src/app/
    sdi:
      container_name: sdi
      tty: true
      build:
          context: .
          dockerfile: Dockerfile
      env_file:
        - env
      ports:
          - "8999:8080"
      depends_on:
        db:
          condition: service_healthy
      networks:
        - sdi
    

networks:
  sdi:
    driver: bridge
